### ISSUE TITLE
Aura Router Integration

### ISSUE THREAD

**Issue by codixor** [Wandu/Festival#3]
Hi, I think Integration With https://github.com/auraphp/Aura.Router as this one is PSR7 ready. and have a nice urlgenerator. very helpful that will be handled with Wandu/DI.

**Comment by wan2land** [comment]
I'm sorry for being so late.
Because the Festival is now under development, also it'll consider the matter(Aura.Router).
But I think maybe the router is also available because I am developing it.
But maybe the [router](https://github.com/wandu/router) is also under development(Based on [FastRoute](https://github.com/nikic/FastRoute)), I think to use it.
